---
title: "A6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r}
#load libraries
library(tidyverse)
library(sf)
library(tigris)
library(censusapi)
library(leaflet)

Sys.setenv(CENSUS_KEY="c8aa67e4086b4b5ce3a8717f59faa9a28f611dab")

```

```{r}

pums_2019_1yr <- getCensus(
  name = "acs/acs1/pums",
  vintage = 2019,
  region = "public use microdata area:*", 
  regionin = "state:06",
  vars = c(
    "SERIALNO",
    "SPORDER",
    "PWGTP",
    "WGTP",
    "NP",
    "HINCP",
    "RWAT",
    "YBL",
    "BLD",
    "TEN",
    "MV",
    "AGEP"
  )
)

```

Map of SF:
```{r}

ca_pumas <-
  pumas("CA", cb = T, progress_bar = F) 

sf_boundary <-
  counties("CA", cb = T, progress_bar = F) %>%
  filter(NAME == "San Francisco")

sf_pumas <-
  ca_pumas %>% 
  st_centroid() %>% 
  .[sf_boundary, ] %>% 
  st_drop_geometry() %>% 
  left_join(ca_pumas %>% select(GEOID10)) %>% 
  st_as_sf()

sf_pums <-
  pums_2019_1yr %>% 
  mutate(
    PUMA = str_pad(public_use_microdata_area,5,"left","0")
  ) %>% 
  filter(PUMA %in% sf_pumas$PUMACE10)

leaflet() %>%
  addTiles() %>% 
  addPolygons(
    data = sf_pumas,
    color = "gray",
    opacity = 0.7,
    fillOpacity = 0.3,
    weight = 1.5
    )

```

```{r}

sf_pums_clean <- sf_pums %>%
  mutate(
    YBL = as.numeric(YBL),
    AGEP = as.numeric(AGEP),
    HINCP = as.numeric(HINCP)
  ) %>% 
  filter(YBL %in% 1:3) %>% 
  arrange(AGEP) %>% 
  group_by(SERIALNO) %>% 
  summarize_all(first)

sf_pums_sorted <-
  sf_pums_clean %>%
  mutate(
    building = BLD %>% 
      factor(
        levels = sf_pums$BLD %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    tenure = TEN %>%
      factor(
        levels = sf_pums$TEN %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    movein = MV %>%
      factor(
        levels = sf_pums$MV %>% 
          unique() %>%
          as.numeric() %>% 
          sort()
      ),
    puma = PUMA %>%
      factor(
        levels = sf_pums$PUMA %>% 
          unique() %>%
          sort()
      )
  )

```

Logit Model 
```{r}

logit_model <- glm(
  leadrisk ~ BLD + TEN + MV + PUMA,
  family = quasibinomial(),
  data = sf_pums_sorted
)

exp(coef(logit_model))
exp(coef(logit_model))/(exp(coef(logit_model))+1)
summary(logit_model)

sample_predict <- sample_n(sf_pums_sorted, 1)
predict(logit_model, sample_predict, type = "response")

```
Sort Leadrisk 
```{r}

sf_pums_predicted <- sf_pums_sorted %>% 
  mutate(predict = predict(logit_model, sf_pums_sorted, type = "response"))

summary_2x2 <-
  sf_pums_predicted %>% 
  mutate(
    leadrisk = ifelse(
      leadrisk == 1, 
      "yes", 
      "no"
    ),
    yes = ifelse(
      predict >= 0.1, 
      as.numeric(WGTP),
      0
    ),
      no = ifelse(
      predict <= 0.1, 
      as.numeric(WGTP),
      0
      
  )) %>% 
group_by(leadrisk) %>% 
summarize(
  `yes` = sum(yes),  
  `no` = sum(no)
)

summary_2x2

```